type = "Snake"
entrypoint = "snake_diffusion.dweam_game:SnakeDiffusionGame"
repo_link = "https://github.com/juraam/snake-diffusion"
thumbnail_dir = "thumbnails"

# Game-specific metadata
[games.snake]
title = "Snake"
tags = ["Top Down"]
description = "A model of the classic Snake game"

[games.snake.buttons]
"â¬†ï¸ Up" = "W"
"â¬…ï¸ Left" = "A"
"â¬‡ï¸ Down" = "S"
"â¡ï¸ Right" = "D"
"ğŸ”„ Reset" = "Enter"